services:
  nginx:
    image: nginx:1.27-alpine
    container_name: velveta-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "8080:8080"
      - "8082:8082"
    volumes:
      - /opt/velveta/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /opt/velveta/nginx/conf.d:/etc/nginx/conf.d:ro
      - /opt/velveta/nginx/sites-enabled:/etc/nginx/sites-enabled:ro
    networks:
      - default
      - prod-frappe
      - prod-nextjs

networks:
  default:
  prod-frappe:
    external: true
    name: frappe_default
  prod-nextjs:
    external: true
    name: nextjs_default
